### ISSUE TITLE
Compute sufficient statistics

### ISSUE THREAD

**Issue by antonarr** [snlab-ch/goldfish#11]
Dear all, 

Thanks for the amazing work you are all doing.
**I was wondering if there was a way to compute relevant sufficient statistics from a dataset which is adapted to the DyNAMs.**

As a matter of an example: 
compute the indegree statistics for the rate submodel. As far as I understood there should be an array of statistics indexed both by sender and by event time. Hence, if I have 70 nodes and 200 ties I should have 70*200 of such statistics, right? 

I was trying to use the degreeStat function in the rem package but it computes indegree per event which is not what such a model should do right? 

Thanks again

**Comment by jhollway** [comment]
You can calculate *any* statistics on any time point by obtaining the observed matrix at any particular time point for a `network.goldfish` object like so: `as.matrix(network, time = "2020-08-05")` and then using a function from your preferred network package (e.g. `igraph` or `sna`).
