### ISSUE TITLE
Loading Library Issues

### ISSUE THREAD

**Issue by thomascowhitt** [snlab-ch/goldfish#13]
I am installing the latest compiled version of this package v.1.4.8 in Rstudio.

`> install.packages("~/Desktop/goldfish_AllOS/macOS/goldfish_1.4.8.tgz", repos = NULL, type = .Platform$pkgType)`

The package is installed (see attached image)

However, when I attempt to load the library, I get the following error:

`> library(goldfish)
Error: package or namespace load failed for ‘goldfish’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Library/Frameworks/R.framework/Versions/4.0/Resources/library/goldfish/libs/goldfish.so':
  dlopen(/Library/Frameworks/R.framework/Versions/4.0/Resources/library/goldfish/libs/goldfish.so, 6): Library not loaded: /usr/local/gfortran/lib/libgfortran.5.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/4.0/Resources/library/goldfish/libs/goldfish.so
  Reason: image not found
`

<img width="597" alt="Screen Shot 2020-08-10 at 11 49 53 AM" src="https://user-images.githubusercontent.com/58599766/89775489-ced80280-daff-11ea-8505-c4ab75136155.png">

**Comment by jhollway** [comment]
Hi Thomas, can you try removing the package, restarting R/RStudio, and reinstall the compiled package?

**Comment by thomascowhitt** [comment]
No luck...

`remove.packages("goldfish", lib="~/Library/R/4.0/library")

Restarting R session...

> install.packages("~/Desktop/goldfish_AllOS/macOS/goldfish_1.4.8.tgz", repos = NULL, type = .Platform$pkgType, lib="/Library/Frameworks/R.framework/Versions/4.0/Resources/library")
> library(goldfish)
Error: package or namespace load failed for ‘goldfish’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Library/Frameworks/R.framework/Versions/4.0/Resources/library/goldfish/libs/goldfish.so':
  dlopen(/Library/Frameworks/R.framework/Versions/4.0/Resources/library/goldfish/libs/goldfish.so, 6): Library not loaded: /usr/local/gfortran/lib/libgfortran.5.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/4.0/Resources/library/goldfish/libs/goldfish.so
  Reason: image not found
> `

**Comment by thomascowhitt** [comment]
Hi auzaheta,

Any chance you can help with this issue?

**Comment by auzaheta** [comment]
Sorry for the late response. Could you provide additional info about your OS(e.g., MacOS Mojave 10.14.6)?
Also, do you have the same problem when you load the `Rcpp` or `RcppArmadillo`. 

If you don't have issues loading those packages can be the case that the binary provided by us doesn't work for your specific OS. Then it'd be better to build the package from the source (like using `remotes` to install the package from GitHub).

**Comment by thomascowhitt** [comment]
No problem- thanks for responding.

I'm using macOS Catalina version 10.15.4

I downloaded the CCP 1.1.tgz binary for macOS (r-release) and attempted to instal via terminal with: `R CMD INSTALL -l /path/to/CCP_1.1.tgz`

I get: `Error: ERROR: no packages specified` (which is the same error I get when I attempt to use my terminal to instal the `goldfish_1.4.8.tgz` file from the `goldfish_AllOS.zip`

When I use remotes and attempt the download from GitHub, I get the following:

`> remotes::install_github("snlab-ch/goldfish")
Downloading GitHub repo snlab-ch/goldfish@HEAD
✓  checking for file ‘/private/var/folders/dx/26yvzpbn7gn00fknvp30gf_40000gn/T/Rtmp5lZTQI/remotesc413d0b1e87/snlab-ch-goldfish-4a2fc02/DESCRIPTION’ ...
─  preparing ‘goldfish’:
✓  checking DESCRIPTION meta-information ...
─  cleaning src
─  running ‘cleanup’
─  installing the package to process help pages (350ms)
         -----------------------------------
─  installing *source* package ‘goldfish’ ...
   ** using staged installation
   checking whether the C++ compiler works... yes
   checking for C++ compiler default output file name... a.out
   checking for suffix of executables... 
   checking whether we are cross compiling... no
   checking for suffix of object files... o
   checking whether we are using the GNU C++ compiler... yes
   checking whether clang++ -mmacosx-version-min=10.13 -std=gnu++11 accepts -g... yes
   checking how to run the C++ preprocessor... clang++ -mmacosx-version-min=10.13 -std=gnu++11 -E
   checking whether we are using the GNU C++ compiler... (cached) yes
   checking whether clang++ -mmacosx-version-min=10.13 -std=gnu++11 accepts -g... (cached) yes
   checking whether g++ version is sufficient... almost
   configure: WARNING: Compiler self-identifies as being compliant with GNUC extensions but is not g++.
   checking for macOS... found
   checking for macOS Apple compiler... not found
   checking for clang compiler... found
   checking for OpenMP compatible version of clang... not found
   configure: WARNING: OpenMP unavailable and turned off.
   checking LAPACK_LIBS... R-supplied partial LAPACK found
   configure: WARNING: Some complex-valued LAPACK functions may not be available
   configure: creating ./config.status
   config.status: creating src/Makevars
   ** libs
   clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c DyNAM_MM_default.cpp -o DyNAM_MM_default.o
   clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c DyNAM_choice_default.cpp -o DyNAM_choice_default.o
   clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c DyNAM_rate_default.cpp -o DyNAM_rate_default.o
   clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c DyNAM_rate_ordered_default.cpp -o DyNAM_rate_ordered_default.o
   clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c REM_default.cpp -o REM_default.o
   clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c REM_ordered_default.cpp -o REM_ordered_default.o
   clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c RcppExports.cpp -o RcppExports.o
   clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c compute_coordination_selection.cpp -o compute_coordination_selection.o
   clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c compute_multinomial_selection.cpp -o compute_multinomial_selection.o
   clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c compute_poisson_selection.cpp -o compute_poisson_selection.o
   clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c convert_rdata_to_cdata.cpp -o convert_rdata_to_cdata.o
   clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c gather_progress.cpp -o gather_progress.o
   clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c gather_receiver_model.cpp -o gather_receiver_model.o
   clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c gather_sender_model.cpp -o gather_sender_model.o
   clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c gather_sender_receiver_model.cpp -o gather_sender_receiver_model.o
   clang++ -mmacosx-version-min=10.13 -std=gnu++11 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o goldfish.so DyNAM_MM_default.o DyNAM_choice_default.o DyNAM_rate_default.o DyNAM_rate_ordered_default.o REM_default.o REM_ordered_default.o RcppExports.o compute_coordination_selection.o compute_multinomial_selection.o compute_poisson_selection.o convert_rdata_to_cdata.o gather_progress.o gather_receiver_model.o gather_sender_model.o gather_sender_receiver_model.o -L/Library/Frameworks/R.framework/Resources/lib -lRlapack -L/Library/Frameworks/R.framework/Resources/lib -lRblas -L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin18/8.2.0 -L/usr/local/gfortran/lib -lgfortran -lquadmath -lm -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
   ld: warning: directory not found for option '-L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin18/8.2.0'
   ld: warning: directory not found for option '-L/usr/local/gfortran/lib'
   ld: library not found for -lgfortran
   clang: error: linker command failed with exit code 1 (use -v to see invocation)
   make: *** [goldfish.so] Error 1
   ERROR: compilation failed for package ‘goldfish’
─  removing ‘/private/var/folders/dx/26yvzpbn7gn00fknvp30gf_40000gn/T/RtmpoqbQzx/Rinst4b4779ee699a/goldfish’
         -----------------------------------
   ERROR: package installation failed
Error: Failed to install 'goldfish' from GitHub:
  System command 'R' failed, exit status: 1, stdout + stderr (last 10 lines):
E> clang++ -mmacosx-version-min=10.13 -std=gnu++11 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o goldfish.so DyNAM_MM_default.o DyNAM_choice_default.o DyNAM_rate_default.o DyNAM_rate_ordered_default.o REM_default.o REM_ordered_default.o RcppExports.o compute_coordination_selection.o compute_multinomial_selection.o compute_poisson_selection.o convert_rdata_to_cdata.o gather_progress.o gather_receiver_model.o gather_sender_model.o gather_sender_receiver_model.o -L/Library/Frameworks/R.framework/Resources/lib -lRlapack -L/Library/Frameworks/R.framework/Resources/lib -lRblas -L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin18/8.2.0 -L/usr/local/gfortran/lib -lgfortran -lquadmath -lm -F/Library/Frameworks/R.framework/.. -framework R`

**Comment by thomascowhitt** [comment]
If I attempt to instal the CCP_1.1.tgz file in R with `install.packages("~/Desktop/CCP_1.1.tgz", repos = NULL, type = .Platform$pkgType)`

I get the following:

`> install.packages("~/Desktop/CCP_1.1.tgz", repos = NULL, type = .Platform$pkgType)
Installing package into ‘/Users/thomascowhitt/Library/R/4.0/library’
(as ‘lib’ is unspecified)`

And the instal fails.

**Comment by thomascowhitt** [comment]
I was playing around with OpenMP when I read that mac users might need this to compile the package from source.  Could this have messed up my terminal?  I might have changed some things that I shouldn't have... my terminal does look a bit different.

**Comment by auzaheta** [comment]
Could you try this [tutorial](https://github.com/Rdatatable/data.table/wiki/Installation) to set OpenMP up? 
`data.table` also uses OpenMP and there is a particular suggestion for your OS.

Also please check if you have Fortran installed. You can check using the following code in the console.
```console
gfortran --version
```

**Comment by askebos** [comment]
Hello!

I'm sorry to reopen but I'm having the same issue as @thomascowhitt 
I've gotten as far as installing gcc@8 with Homebrew, but when I try to install goldfish, I get:

`─  installing *source* package ‘goldfish’ ...
   ** using staged installation
   checking whether the C++ compiler works... yes
   checking for C++ compiler default output file name... a.out
   checking for suffix of executables... 
   checking whether we are cross compiling... no
   checking for suffix of object files... o
   checking whether we are using the GNU C++ compiler... yes
   checking whether g++-8 accepts -g... yes
   checking how to run the C++ preprocessor... g++-8 -E
   checking whether we are using the GNU C++ compiler... (cached) yes
   checking whether g++-8 accepts -g... (cached) yes
   checking whether g++ version is sufficient... yes, with OpenMP as version 8.4.0
   checking for macOS... found
   checking for macOS Apple compiler... not found
   checking for clang compiler... not found
   configure: WARNING: unsupported macOS build detected; if anything breaks, you keep the pieces.
   checking LAPACK_LIBS... R-supplied partial LAPACK found
   configure: WARNING: Some complex-valued LAPACK functions may not be available
   checking for OpenMP... missing
   configure: creating ./config.status
   config.status: creating src/Makevars`

So it finds OpenMP, but then...? I've changed the following in `Makeconf`:
```
CC = gcc-8
CXX = g++-8
FLIBS =  FLIBS = -L/usr/local/lib/gcc/8/gcc/x86_64-apple-darwin19/8.4.0 -L/usr/local/lib/gcc/8 -lgfortran -lquadmath -lm
SHLIB_OPENMP_CFLAGS = -fopenmp
```
(The last line following the [data.table tutorial ](https://github.com/Rdatatable/data.table/wiki/Installation); didn't seem to make a difference.)

I'm using MacOS Catalina 10.15.7 and R version 4.0.3.

Any ideas?
