### ISSUE TITLE
Outdated link in README file

### ISSUE THREAD

**Issue by Knieps** [snlab-ch/goldfish#15]
The README file recommends a link with an outdated command `brew install gcc --without-multilib` to install gcc: https://www.infoseczanshin.com/using-openmp-with-r-packages-in-os-x.html 

I suggest replacing the outdated link above with this one:  https://medium.com/biosyntax/following-up-library-dependency-when-compiling-r-packages-89f191b9f227
 This tutorial is more up-to-date and helped me to compile goldfish on my MacOS.

**Comment by jhollway** [comment]
Thanks Melanie, very useful experience!

@auzaheta I've updated the README accordingly, but OpenMP doesn't seem to be working on mine with this `Makeconf`/`Makevars`:

```
...
checking for OpenMP compatible version of clang... not found
checking LAPACK_LIBS... configure: WARNING: OpenMP unavailable and turned off.
R-supplied partial LAPACK found
...
```
