### ISSUE TITLE
Structural zeros for two-mode networks

### ISSUE THREAD

**Issue by SimonMontfort** [snlab-ch/goldfish#23]
Some time ago, it was not possible to introduce structural zeros for two-mode networks. If there are geographic constraints for nodes to form ties with other nodes as it may often be the case in water governance (e.g. Geneva and Graubünden have little reason to form a multilateral agreement because they do not share rivers), we'd need to restrict the risk set. Would it be possible to implement structural zeros for two-mode networks?

**Comment by auzaheta** [comment]
A more general solution is coming along the way with the DyNAM-i model (it's now on the branch with the same name).  @marion-hoffman introduced the `opportunitiesList` parameter that could be fed on the `estimationInit` argument. It helps to restrict the risk set.  This branch is still under testing and documentation. Hopefully, it will be soon merged with the develop branch.

**Comment by SimonMontfort** [comment]
thank you so much for the response! I really look forward to trying it out when it will be merged to the master.
