### ISSUE TITLE
Choice-coordination wrong likelihood computation when nodes are not present

### ISSUE THREAD

**Issue by auzaheta** [snlab-ch/goldfish#37]
**Describe the bug**
Computation of the likelihood in the choice coordination doesn't exclude from the computation the nodes not present. 

**To Reproduce**
```r
# # observed relational events
eventsMM <- data.frame(
  time = cumsum(
    c(1, 5, 3, 4, 2)),
  sender = sprintf(
    "Actor %d", 
    c(1, 3, 2, 5, 5)),
  receiver = sprintf(
    "Actor %d", 
    c(2, 2, 4, 1, 1)),
  increment =
    c(1, 2, 1, 1, 1),
  stringsAsFactors = FALSE
)

# # actors attributes
actorsMM <- data.frame(
  label = sprintf("Actor %d", 1:5),
  present = c(rep(TRUE, 4), FALSE),
  # present = rep(TRUE, 5),
  attr1 = c(9.9, 0.1, 0.5, 0.45, 0.25),
  attr2 = c(1, 2, 1, 2, 1),
  stringsAsFactors = FALSE
)

# # actors change present
presentChange <- data.frame(
  time = 10,
  node = "Actor 5",
  replace = TRUE
)

# # state at the beginning of the network
networkMM <- matrix(
  c(0, 3, 2, 0, 0,
    3, 0, 0, 0, 0,
    2, 0, 0, 1, 0,
    0, 0, 1, 0, 0,
    0, 0, 0, 0, 0), 
  nrow = 5, ncol = 5, byrow = TRUE,
  dimnames = list(sprintf("Actor %d", 1:5),
                  sprintf("Actor %d", 1:5))
)

# defining objects
actorsMM <- defineNodes(actorsMM)
actorsMM <- linkEvents(actorsMM, changeEvents = presentChange, attribute = "present")
networkMM <- defineNetwork(
  matrix = networkMM, nodes = actorsMM,
  directed = FALSE)
networkMM <- linkEvents(
  x = networkMM,
  changeEvent = eventsMM,
  nodes = actorsMM)
depNetMM <- defineDependentEvents(
  events = eventsMM,
  nodes = actorsMM,
  defaultNetwork = networkMM)

# model
mod01 <- estimate(depNetMM ~ inertia + trans,
                  model = "DyNAM", subModel = "choice_coordination",
                  estimationInit = list(returnIntervalLogL = TRUE,
                                        returnEventProbabilities = TRUE),
                  verbose = TRUE)
```
```r
> Likelihood: -11.51293 in iteration 1 
> Parameters: 0, 0 
> Score: 0.25, -0.75
> Update: 0.00367483296213808, -0.0181514476614699
> Damping factor: 10
```

**Expected behavior**
The expected likelihood for the initial parameters `c(0, 0)` should be: `3 * log(1/6) + 2 * log(1/10)`. The first three events happen without "Actor 5", then the likelihood of a tie is 1 / choose(4,2) = 1/6. The last two with five nodes present, the likelihood of a tie is 1 / choose(5, 2) = 1/10. 

It computes `5 * log(1/10)`, which results when all nodes are present.

**Desktop:**
 - OS: Windows 10 Education
 - R Version 4.0.3
 - Goldfish Version 1.5.0

**Comment by marion-hoffman** [comment]
I looked it up, and a change had been done to the code and created a mistake. This mistake led to a wrong initialization of the nodeset composition in the algorithm, so this was also wrong for all models actually. I corrected the R engine, now the behavior of the given script is correct.
I also checked, the C engine seems correct to me, and I suspect this is because the change that created the error was done after the C engine was created from the R engine.

So for me, this is fixed, but please check if you want @auzaheta :)

**Comment by auzaheta** [comment]
It seems the changes in preprocessing fire up some errors for the choice-coordination example.  Now, some updates give the warning: You are dissolving a tie which doesn't exist!

Even worst, the model with `ignoreRep` doesn't work.

More check-ups are on the way. Keep you posted.

**Comment by marion-hoffman** [comment]
Which changes to the preprocessing are you referring to? I only changed the estimation engine here.
Happy to look at this issue further if you have an example of a script not working, what I tried so far seemed to work fine.

**Comment by auzaheta** [comment]
Sorry, my mistake. I should have run the model with a weird in-between version of the package.

After double-checking today.  I changed the environment used in the estimation engine.
The problem is that the `PrepEnvir` contains the changes after preprocessing. The estimation engine routines expect the objects without the events changes applied to the objects. I hope it makes sense.

The solution is to feed and new environment to the estimation routine in a similar way to how the environment is defined for the preprocessing. I committed those changes to the develop branch. Now, the CRAN checks should pass.

The following code was giving an error

```r
data("Fisheries_Treaties_6070")

states <- defineNodes(states)
states <- linkEvents(states, sovchanges, attribute = "present")
states <- linkEvents(states, regchanges, attribute = "regime")
states <- linkEvents(states, gdpchanges, attribute = "gdp")

bilatnet <- defineNetwork(bilatnet, nodes = states, directed = FALSE)
bilatnet <- linkEvents(bilatnet, bilatchanges, nodes = states)

createBilat <- defineDependentEvents(events = bilatchanges[bilatchanges$increment == 1, ], 
                                     nodes = states, 
                                     defaultNetwork = bilatnet)

contignet <- defineNetwork(contignet, nodes = states, directed = FALSE)
contignet <- linkEvents(contignet, contigchanges, nodes = states)

#  model doesn't converge
partnerModel <- estimate(
  createBilat ~
    inertia(bilatnet) +
    indeg(bilatnet, ignoreRep = TRUE) +
    trans(bilatnet, ignoreRep = TRUE) +
    tie(contignet) +
    alter(states$regime) +
    diff(states$regime) +
    alter(states$gdp) +
    diff(states$gdp),
  model = "DyNAM", subModel = "choice_coordination",
  estimationInit = list(initialDamping = 40, maxIterations = 30)
)

> Error: Error in DyNAM choice_coordination estimation: Error in estimate_int(initialDamping = 40, maxIterations = 30, statsList = structure(list(: Matrix cannot be inverted; probably due to collinearity between parameters.

# model that convergence
pmStats <- estimate(
  createBilat ~
    inertia(bilatnet) +
    indeg(bilatnet, ignoreRep = TRUE) +
    trans(bilatnet, ignoreRep = TRUE) +
    tie(contignet) +
    alter(states$regime) +
    diff(states$regime) +
    alter(states$gdp) +
    diff(states$gdp),
  model = "DyNAM", subModel = "choice_coordination",
  preprocessingOnly = TRUE
)

partnerModel <- estimate(
  createBilat ~
    inertia(bilatnet) +
    indeg(bilatnet, ignoreRep = TRUE) +
    trans(bilatnet, ignoreRep = TRUE) +
    tie(contignet) +
    alter(states$regime) +
    diff(states$regime) +
    alter(states$gdp) +
    diff(states$gdp),
  model = "DyNAM", subModel = "choice_coordination",
  estimationInit = list(initialDamping = 40, maxIterations = 30),
  preprocessingInit = pmStats
)

summary(partnerModel)
```
