### ISSUE TITLE
Code coverage action not completing

### ISSUE THREAD

**Issue by jhollway** [snlab-ch/goldfish#5]
Added `covr::codecov()` to the workflow, along with a secret to the repository, but isn't calculating or uploading to codecov.io for analytic purposes.

Perhaps incorrectly located in workflow script?

**Comment by auzaheta** [comment]
I tried to run locally the `covr::codecov()`, and it fails. As far I could trace down the problem, we have to change or adapt the unit root testing to avoid the fail.

**Comment by mirkoreul** [comment]
Yup, though I'm not sure yet about the exact source of the error. 

In my case, running locally on commit 34a072cb380070c0db1298f4d5ed36e3d7bfbb81:
```
remove.packages("goldfish")
library("devtools")
devtools::install(".")
devtools::load_all()
covr::codecov()
```
Yields:
```
Failure in `/tmp/RtmpQDCbjl/R_LIBS47fe20ee2774/goldfish/goldfish-tests/testthat.Rout.fail`
etLoadedDLLs()
Calls: <Anonymous> ... assignNativeRoutines -> getDLLRegisteredRoutines.DLLInfo
In addition: Warning message:
S3 methods ‘AIC.result.goldfish’, ‘BIC.result.goldfish’, ‘as.data.frame.nodes.goldfish’, ‘as.matrix.network.goldfish’, ‘coef.result.goldfish’, ‘estimate.formula’, ‘head.dependent.goldfish’, ‘head.network.goldfish’, ‘head.nodes.goldfish’, ‘linkEvents.default’, ‘linkEvents.network.goldfish’, ‘linkEvents.nodes.goldfish’, ‘logLik.result.goldfish’, ‘print.dependent.goldfish’, ‘print.network.goldfish’, ‘print.nodes.goldfish’, ‘print.preprocessed.goldfish’, ‘print.result.goldfish’, ‘print.summary.result.goldfish’, ‘summary.result.goldfish’, ‘tail.dependent.goldfish’, ‘tail.network.goldfish’, ‘tail.nodes.goldfish’ were declared in NAMESPACE but not found 
Execution halted
```

And  `devtools::check()`, which [apprently is used by codecov internally](https://github.com/r-lib/covr/issues/290#issuecomment-342626489), yields:
```
The following object is masked from 'package:devtools':

    test_file

> # library(goldfish)
> devtools::load_all(".")
Error: No root directory found in /tmp/RtmpQDCbjl/goldfish.Rcheck/tests or its parent directories. Root criterion: contains a file `DESCRIPTION`
Execution halted
```

Could you confirm that you get these errors as well @auzaheta?

If so this may be related to [this issue](https://github.com/r-lib/testthat/issues/720), or possibly unnecessary files like [tests/testthat.R file](https://github.com/snlab-ch/goldfish/blob/master/tests/testthat.R).
Removing the `tests/testthat.R` file and re-running `devtools::check()` actually generates more specific errors, such as:
```
> checking examples ... ERROR
  Running examples in ‘goldfish-Ex.R’ failed
  The error most likely occurred in:
  
  > base::assign(".ptime", proc.time(), pos = "CheckExEnv")
  > ### Name: defineDependentEvents
  > ### Title: Define dependent events for a model
  > ### Aliases: defineDependentEvents
  > 
  > ### ** Examples
  > 
  > actors <- data.frame(
  +   actor = 1:5, label = paste("Actor", 1:5),
  +   present = TRUE, gender = sample.int(2, 5, replace = TRUE)
  + )
  > actors <- defineNodes(nodes = actors)
  Error in defineNodes(nodes = actors) : 
    The nodeset couldn't be constructed:  The column “label” expects values of type character.
  Calls: defineNodes ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
  Execution halted
```

Adjusting or removing those files might fix the issue, though I admit the testing could use an overhaul in any case.

**Comment by auzaheta** [comment]
@mirkoreul I get the same errors but I could resolve one. Now running locally on commit 94dc5027fa2b6f7f2dbd5f923c28b2b1cce874b7:

``` r
covr::codecov()
``` 

Yields:

```r
Error: Failure in `C:/Users/ualvaro/AppData/Local/Temp/Rtmpw7vAOZ/R_LIBS124450e2b8b/goldfish/goldfish-tests/testthat.Rout.fail`
.nodes.goldfish', 'as.matrix.network.goldfish', 'coef.result.goldfish', 'estimate.formula', 'head.dependent.goldfish', 'head.network.goldfish', 'head.nodes.goldfish', 'linkEvents.default', 'linkEvents.network.goldfish', 'linkEvents.nodes.goldfish', 'logLik.result.goldfish', 'print.dependent.goldfish', 'print.network.goldfish', 'print.nodes.goldfish', 'print.preprocessed.goldfish', 'print.result.goldfish', 'print.summary.result.goldfish', 'summary.result.goldfish', 'tail.dependent.goldfish', 'tail.network.goldfish', 'tail.nodes.goldfish' were declared in NAMESPACE but not found 
2: In setup_ns_exports(path, export_all, export_imports) :
  Objects listed as exports, but not present in namespace: defineDependentEvents, defineGlobalAttribute, defineNetwork, defineNodes, estimate, examine.changepoints, examine.outliers, goldfishObjects, linkEvents
Execution halted
```

I also think it is related to [this issue](https://github.com/r-lib/testthat/issues/720) but I don't really get how to solve that. 
Additionally, running the test with:

```r
devtools::test()
```

Yields:
```r
Loading goldfish
  <")))><  The Goldfish package in R

goldfish: version 1.4.3, "Bristol Shubunkins", created on 2020-05-17

Testing goldfish
√ |  OK F W S | Context
x |   8 1     | functions_effects_DyNAM_choice-init_default
--------------------------------------------------------------------------------
test-functions_effects_DyNAM_choice-init_default.R:49: error: DyNAM default and tertius-diff init return the same result
object of type 'builtin' is not subsettable
Backtrace:
 1. testthat::expect_equal(...) C:\Users\ualvaro\Documents\phdLocal\sp2020\ghfork\goldfish/tests/testthat/test-functions_effects_DyNAM_choice-init_default.R:49:2
 4. goldfish::init_DyNAM_choice.tertius_diff(...)
 5. base::apply(...) R/functions_effects_DyNAM_choice.R:2344:2
 6. goldfish:::FUN(newX[, I], ...)
...
```

I didn't have those in R 3.6.3 and also when I run the test in the console after `devtools::load_all()`. I don't get those errors.

**Comment by mirkoreul** [comment]
Okay, I can't reproduce your second error for `devtools::test()` on either 94dc5027fa2b6f7f2dbd5f923c28b2b1cce874b7 or the current head 67d24a88899f8faf54fff21a999aff1d1ba2b1cd. I instead get a couple of test failures, which may be unrelated, see https://github.com/snlab-ch/goldfish/issues/6.

Our `covr::codecov()` errors appear to refer to the same problem though:
```
> covr::codecov()
Fehler: Failure in `/tmp/RtmpcZc8Ip/R_LIBS7177792a5f82/goldfish/goldfish-tests/testthat.Rout.fail`
Calls: <Anonymous> ... testthat_source_test_helpers -> source_dir -> lapply -> FUN -> eval -> eval
In addition: Warning message:
S3 methods ‘AIC.result.goldfish’, ‘BIC.result.goldfish’, ‘as.data.frame.nodes.goldfish’, ‘as.matrix.network.goldfish’, ‘coef.result.goldfish’, ‘estimate.formula’, ‘head.dependent.goldfish’, ‘head.network.goldfish’, ‘head.nodes.goldfish’, ‘linkEvents.default’, ‘linkEvents.network.goldfish’, ‘linkEvents.nodes.goldfish’, ‘logLik.result.goldfish’, ‘print.dependent.goldfish’, ‘print.network.goldfish’, ‘print.nodes.goldfish’, ‘print.preprocessed.goldfish’, ‘print.result.goldfish’, ‘print.summary.result.goldfish’, ‘summary.result.goldfish’, ‘tail.dependent.goldfish’, ‘tail.network.goldfish’, ‘tail.nodes.goldfish’ were declared in NAMESPACE but not found 
Execution halted
```

Maybe if I clean up some of the helper_* files and move some of the code of the more "integrative" tests into separate helper_* files, it will become clearer how to fix this.

**Comment by mirkoreul** [comment]
I think it is a scoping issue, and it is raised for all interface tests which rely on prepared Goldfish objects. Below is a full stack trace. 

For now I have removed these tests.
I've been testing the workaround suggested in the testthat scoping issue, assigning all objects using: `assign("object", object, env = .GlobalEnv)`, but since our issue is not exactly the same and I didn't get it to work for all tests yet, I'm thinking it may be cleaner to re-write at least some of the interface tests.

It could also be a problem with goldfish. In `parseFormula` (see error trace below) and [other functions](https://github.com/snlab-ch/goldfish/search?q=envir+%3D+environment%28%29&unscoped_q=envir+%3D+environment%28%29), objects are by default expected to be located in the 'current' environment via `get(depName, envir = envir)`, with `envir = environment()` by default. I don't know enough about this to say if it is a good idea or not.

@auzaheta do we need to re-evaluate the use of `envir = environment()` in these functions, or is this already a 'best-practice' solution, or do you think it isn't related?

@jhollway can we check if codecov runs on the [hotfix-codecov](https://github.com/snlab-ch/goldfish/tree/hotfix-codecov) branch now?

```
> covr::codecov()
2020-06-24 13:00:54.490 FATAL Objekt 'callsDependent' not found
  at get(depName, envir = envir)
  at functions_parsing.R#26: inherits(get(depName, envir = envir), "dependent.goldfish")
  at functions_estimation.R#314: parseFormula(formula, envir = envir)
  at functions_estimation.R#175: estimate.formula(formula, model = model, subModel = subModel, preprocessingOnly = TRUE, silent = TRUE)
  at helper_consistency_updateStat_initStat.R#7: estimate(formula, model = model, subModel = subModel, preprocessingOnly = TRUE, silent = TRUE)
  at eval(exprs, env)
  at eval(exprs, env)
  at FUN(X[[i]], ...)
  at lapply(files, source_file, env = env, chdir = chdir, wrap = wrap)
  at source_dir(path, "^helper.*\\.[rR]$", env = env, wrap = FALSE)
  at source_test_helpers(path, env)
  at test_dir(path = test_path, reporter = reporter, env = env, filter = filter, ..., stop_on_failure = stop_on_failure, stop_on_warning = stop_on_warning, wrap = wrap)
  at test_package_dir(package = package, test_path = test_path, filter = filter, reporter = reporter, ..., stop_on_failure = stop_on_failure, stop_on_warning = stop_on_warning)
  at #53: testthat::test_package("goldfish")
  at #53: withVisible(expr)
  at #53: withCallingHandlers(withVisible(expr), debug = logger, message = logger, warning = logger, caughtError = logger, error = logger)
```

**Comment by auzaheta** [comment]
@mirkoreul, thanks for the info. That is an excellent question. I don't have an answer, and I don't know what the best-practices are. 

I included the `envir` parameter in all the functions that uses `get` in 67d24a88899f8faf54fff21a999aff1d1ba2b1cd to avoid the names conflict between parameter functions and users objects names. However, I'm happy to read recommendations about it, maybe @stadtfeldethz or @marion-hoffman may have a suggestion.

The environment is set in `estimate()`, and it is passed to all other functions, except preprocessing where it needs the local environment. I think it should be possible to create an environment object with the objects for testing. 

A second alternative would be to rename all internal parameters to avoid conflicts. However, this issue is before that 67d24a88899 commit. Then, all the functions that use `get` have the scoping issue for testing.

**Comment by jhollway** [comment]
@mirkoreul I've folded the codecov into the main build job in the Github Action workflow so that it should inherit the package setup. Bit of a trial though: can you create a pull-request? That should trigger the workflow and we'll see whether that works.
