### ISSUE TITLE
opportunitiesList seems not to be considered for model estimation

### ISSUE THREAD

**Issue by hnunner** [snlab-ch/goldfish#55]
**opportunitiesList for "estimate(..., estimationInit, ...)" seems not to be considered for model estimation**
When adding opportunity lists to DyNAM network model, they seem not to be considered for model estimation, as results do not differ between models with and without opportunity lists.

**To Reproduce**

**Expected behavior**
Effects should differ between a model that is estimating effects considering the entire network, and models that are constrained by opportunities limiting the network to only a subset of nodes.

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.7 (19H1519)
 - R Version 4.1.1 (2021-08-10) -- "Kick Things"
 - RStudio Version 2021.09.0 Build 351
- Goldfish Version 1.5.1

**Comment by marion-hoffman** [comment]
I have pushed a correction to the develop branch. I checked with DyNAM-i and it seems to do the trick, but you might want to test with your script (@hnunner or @auzaheta). 
I hope it is solved :)

**Comment by auzaheta** [comment]
PR 1.6.2 includes 18add40a8dd8622db68229d5198fafd4eccac09c commit solving it.
