### ISSUE TITLE
Unable to load on MacOS with new chip 

### ISSUE THREAD

**Issue by cpuga4** [snlab-ch/goldfish#57]
I am on a new mac laptop trying to load goldfish on RStudio. 

1. I downloaded the .tgz macOS file from github
2. In RStudio, I went to install from package archive file 
3. I selected the downloaded .tgz file 
4. It downloaded 
5. I used the code library(goldfish) to try and load the package 
6. I received the error message below: 

```
Error: package or namespace load failed for ‘goldfish’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Library/Frameworks/R.framework/Versions/4.1/Resources/library/goldfish/libs/goldfish.so':
  dlopen(/Library/Frameworks/R.framework/Versions/4.1/Resources/library/goldfish/libs/goldfish.so, 6): Library not loaded: /usr/local/gfortran/lib/libgfortran.5.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/4.1/Resources/library/goldfish/libs/goldfish.so
  Reason: image not found
```

**Expected behavior**
I expected the package to load. Prof. Hollway indicated that this is an issue with my computer processing chip. 

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur v. 11.2.2
 - Chip: Apple M1
 - R Version 4.1.1 High Sierra Build 
 - RStudio Version 2021.09.0
- Goldfish Version 1.5.1

**Additional context**

**Comment by jhollway** [comment]
@auzaheta, is this just a case of adding another address to look for gfortran on Mac systems with the new M1 processor, or do the binaries need to be built differently, e.g. by [CRAN](https://cran.r-project.org/web/checks/check_flavors.html#r-release-macos-arm64) or is there a Github workflow that we can use to produce such a binary?

**Comment by auzaheta** [comment]
@cpuga4, could you check the path where `gfortran` is installed? From the terminal, you can run the following lines to find the paths:

```shell
which gfortran

gfortran -print-file-name=libgfortran.dylib | xargs dirname
```

Other M1 users reported that installing `gcc` with homebrew doesn't automatically install `gfortran`. You can install `gfortran` from [here](https://github.com/fxcoudert/gfortran-for-macOS/releases) if you don't have it.

Otherwise, let me know. I can post the content of a makevars file that will allow installing `goldfish`  using `remotes`.

**Comment by auzaheta** [comment]
@cpuga4, I'll close this and refer to the links in the previous comment when macOS instructions are updated. 

Feel free to follow with comments over this topic on issue #62
