### ISSUE TITLE
Offer verbose options and/or S3 print methods

### ISSUE THREAD

**Issue by jhollway** [snlab-ch/goldfish#69]
> You write information messages to the console that cannot be easily suppressed. It is more R like to generate objects that can be used to extract the information a user is interested in, and then print() that object.
> Instead of cat() rather use message()/warning()  or if(verbose)cat(..) (or maybe stop()) if you really have to write text to the console.
> (except for print, summary, interactive functions)

**Comment by auzaheta** [comment]
@marion-hoffman, I modified the `defineGroups_interaction()` to include a `verbose` argument and all `cat()` calls are now conditional on `verbose = TRUE`.

I also changed `silent -> verbose` and `verbose -> debug`. BTW, the `C++` engines already had the messages with additional information as the `R` engine.

Everything to be checked to be working on DyNAMi

**Comment by marion-hoffman** [comment]
I have checked and it works! I changed the verbose part (or progress now) in the dynam-i part, there was way too much being showed so far.
