### ISSUE TITLE
Avoid relying on global environment

### ISSUE THREAD

**Issue by jhollway** [snlab-ch/goldfish#70]
> Please do not modifiy the .GlobalEnv. This is not allowed by the CRAN policies.

**Comment by marion-hoffman** [comment]
I checked the dynam-i part with the new environment solution and it seems to be fine (the code looks fine to me and all scripts are running fine).

**Comment by marion-hoffman** [comment]
@auzaheta I found some instances of the use of the get() function in the estimation engine functions, wehre we don't rely on the local environment. I put the comment "# add prepEnvir" in the script "functions_estimation_engine.R" at the problematic places. I made one commit where I just added the comments, and two other commits where I propose a solution. 
Can you have a look ? If I did something wrong, please revert my changes!

**Comment by marion-hoffman** [comment]
I saw that some checks were no longer workings after these corrections. Please check commits number 4926857, b2ab820, 0422c25, and tell me what I missed?
