### ISSUE TITLE
Unknown or uninitialised column: `replace`

### ISSUE THREAD

**Issue by jhollway** [snlab-ch/goldfish#79]
When calling `linkEvents.network.goldfish()` with incremented change events, the following warning message appears:

```
Warning message:
Unknown or uninitialised column: `replace`. 
```

Could be that this emerges from `checkEvents.network.goldfish()` when it searches for one or the other.

Since the function otherwise works, this warning should be avoided or suppressed.

**Comment by auzaheta** [comment]
Could you post a repex?

`Social_Evolution example` had incremented change events and the warning doesn't appear. 

```r
data("Social_Evolution")
callNetwork <- defineNetwork(nodes = actors, directed = TRUE)
callNetwork <- linkEvents(x = callNetwork, changeEvent = calls,
                          nodes = actors)

head(calls)
>         time   sender receiver increment
> 1 1220733470 Actor 72 Actor 50         1
> 2 1221102974 Actor 43 Actor 51         1
> 3 1221784293 Actor 43 Actor 51         1
> 4 1221785882 Actor 43 Actor 22         1
> 5 1221787264 Actor 43 Actor 55         1
> 6 1221848443 Actor 43 Actor 51         1
```

**Comment by shaunss** [comment]
Yes this seems to be a `tibble` problem:

```
data("Social_Evolution")
calls2 <- as_tibble(calls)
callNetwork <- defineNetwork(nodes = actors, directed = TRUE)
callNetwork <- linkEvents(x = callNetwork, changeEvent = calls2,
                          nodes = actors)

> Warning:
> Unknown or uninitialised column: `replace`. 
```

**Comment by auzaheta** [comment]
Thanks, @shaunss; then I think it'd make sense to change the issue to a feature request asking to support objects of class `tibble`.  It'd imply more than just changes in the `linkEvents()`.
