### ISSUE TITLE
Multilevel/multiplex estimation

### ISSUE THREAD

**Issue by dkarell** [snlab-ch/goldfish#8]
I receive the following error when trying to estimate a model using a multilevel/multiplex network.

> Parsing formula.
> Initializing objects.
> Starting preprocessing.
> Initializing cache objects and statistical matrices.
> Preprocessing events.
>   |**                                                                                     |   2%
> Error in if (!isNodeEvent[nextEvent] && event$replace < 0) { : 
>   missing value where TRUE/FALSE needed

I am not sure if it is a bug. The implementation seems reasonable to me, but I could have missed something. If it is not a bug, consider this a friendly request for a new feature! Thanks in advance.

Data and code to reproduce the error are attached.

[goldfish_multilevel.zip](https://github.com/snlab-ch/goldfish/files/4798992/goldfish_multilevel.zip)

**Desktop (please complete the following information):**
 - MacOS Catalina 10.15.4
 - R Version 3.6.0 
 - RStudio Version 1.2.1335
- Goldfish Version 1.4.2

**Comment by jhollway** [comment]
@auzaheta I'm also getting this error in the dontrun example for `init_REM_choice.indeg`

**Comment by auzaheta** [comment]
@dkarell, thanks for reporting the bug. I'm so sorry that it took so long to check on this.

@dkarell and @jhollway, the current version on the develop branch, had the bug fixed. 

I hope it helps.

**Comment by dkarell** [comment]
@auzaheta No problem, of course! I appreciate you looking into it.
